exports.typeDefs = `

type Query {
	user(id: ID!): User!
  users: [User!]!
	messages(conversationId: ID!): [Message!]!
	conversation(conversationId: ID!): Conversation!
	me: User!
	authData: AuthResponse!
	search(pattern: String!): SearchResponse!
}

type Mutation {
	signUp(
		username: String!
		password: String!
		passwordConfirmation: String!
	): AuthResponse!

	signIn(
		username: String!
		password: String!
	): AuthResponse!

	signOut: AuthResponse!

	startConversation(
		userId: ID!
		label: String
		message: String
	): Conversation!

	createGroup(
		label: String!
	): Conversation!

	sendMessage(
		conversationId: ID!
		text: String!
	): Message!
}

type AuthResponse {
	id: ID!
	isLoggedIn: Boolean!
	sid: String
	user: User
}

type Subscription {
	message: Message!
	newConversation: Conversation!
}

type SearchResponse {
	users: [User!]
}

type User {
	id: ID!
	username: String!
	conversations: [Conversation!]!
}

type Conversation {
	id: ID!
	type: String!
	users: [User!]!
	messages: [Message!]!
	label: String
	lastMessage: Message
}

type Message {
	id: ID!
	user: User!
	text: String!
	conversation: Conversation!
}

`