exports.typeDefs = `

type Query {
	user(id: ID!): User!
  users: [User!]!
	messages(conversationId: ID!): [Message!]!
	me: User!
}

type Mutation {
	signUp(
		username: String!
		password: String!
		passwordConfirmation: String!
	): User!

	signIn(
		username: String!
		password: String!
	): User!

	signOut: Boolean!

	startConversation(
		userId: ID!
		label: String!
	): Conversation!

	sendMessage(
		conversationId: ID!
		text: String!
	): Message!
}

type Subscription {
	message(conversationId: ID!): Message!
}

type User {
	id: ID!
	username: String!
	conversations: [Conversation!]!
}

type Conversation {
	id: ID!
	type: String!
	label: String!
	users: [User!]!
	messages: [Message!]!
	lastMessage: Message
}

type Message {
	id: ID!
	user: User!
	text: String!
}

`